[build]
  # 构建命令
  command = "npm run build"
  
  # 发布目录（Next.js 静态导出的输出目录）
  publish = "out"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

# 处理 SPA 路由 - 将所有路由重定向到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 